// Evaluation keyword sources for the Evaluate a Job page.
//
// IMPLEMENTATION DECISION: Requirements.md requires displaying "strength and
// gaps" after a resume is submitted against a JD, with no API calls and no
// external dependencies ("No external database, no API calls — 100% local").
// The analysis is therefore a deterministic local comparison: keywords found
// in the job description are matched against the resume text. The seed list
// below is a technical starting point for common JD skills; the analysis also
// extracts keywords directly from the JD itself, so the feature works for any
// JD without relying solely on this list.

export const COMMON_SKILL_KEYWORDS: string[] = [
  // Programming languages
  'python',
  'javascript',
  'typescript',
  'java',
  'c++',
  'c#',
  'golang',
  'rust',
  'ruby',
  'php',
  'swift',
  'kotlin',
  'sql',
  'shell',
  'bash',
  'powershell',
  // Web / frontend
  'react',
  'angular',
  'vue',
  'node',
  'node.js',
  'html',
  'css',
  'tailwind',
  'redux',
  'next.js',
  'graphql',
  'rest api',
  'restful',
  // Backend / architecture
  'microservices',
  'distributed systems',
  'system design',
  'api design',
  'aws',
  'azure',
  'gcp',
  'docker',
  'kubernetes',
  'terraform',
  'ci/cd',
  'jenkins',
  'linux',
  'nginx',
  'redis',
  'kafka',
  'rabbitmq',
  'grpc',
  'websockets',
  // Data
  'postgresql',
  'mysql',
  'mongodb',
  'dynamodb',
  'elasticsearch',
  'data pipeline',
  'etl',
  'data modeling',
  'big data',
  'spark',
  'hadoop',
  'airflow',
  // Testing / QA
  'testing',
  'test automation',
  'unit testing',
  'integration testing',
  'e2e',
  'end-to-end testing',
  'cypress',
  'playwright',
  'selenium',
  'jest',
  'pytest',
  'junit',
  'tdd',
  'bdd',
  'ci',
  'quality assurance',
  'qa',
  // AI / ML
  'machine learning',
  'deep learning',
  'nlp',
  'llm',
  'ai',
  'tensorflow',
  'pytorch',
  'scikit-learn',
  'pandas',
  'numpy',
  'rag',
  'prompt engineering',
  // Tools & practices
  'git',
  'github',
  'gitlab',
  'jira',
  'agile',
  'scrum',
  'kanban',
  'code review',
  'pair programming',
  'documentation',
  'mentoring',
  'leadership',
  'communication',
  'collaboration',
  'problem solving',
  'analytical skills',
  'attention to detail',
  'time management',
  // Domain terms
  'web development',
  'mobile development',
  'full-stack',
  'frontend',
  'backend',
  'devops',
  'sre',
  'security',
  'cloud',
  'database',
  'algorithms',
  'data structures',
  'object-oriented',
  'oop',
];
